using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class InterfaceTab : Control
{
    public InterfaceTab()
    {
        RobustXamlLoader.Load(this);

        Control.Initialize();
    }
}

